version: "3.5"

services:
  php:
    container_name: "desafio.php"
    build: images/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    ports:
      - "9000:9000"
    networks:
      - desafio-network

  nginx:
    container_name: "desafio.nginx"
    build: images/nginx
    volumes:
      - ./public:/var/www/html/public
    working_dir: /var/www/html
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    networks:
      - desafio-network

  database:
    container_name: "desafio.database"
    image: mysql:8
    volumes:
      - .docker/mysql/dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: "bridge"
